//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLTTPTEntities : DbContext
    {
        public QLTTPTEntities()
            : base("name=QLTTPTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TTinChuTro> TTinChuTroes { get; set; }
        public virtual DbSet<TTinNguoiThue> TTinNguoiThues { get; set; }
        public virtual DbSet<TTinPhongTro> TTinPhongTroes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
