//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTinChuTro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TTinChuTro()
        {
            this.TTinPhongTroes = new HashSet<TTinPhongTro>();
        }
    
        public int TT { get; set; }
        public string HoTenChuTro { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string SoDienThoai { get; set; }
        public string NoiDKHoKhau { get; set; }
        public int SoLuongPhong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTinPhongTro> TTinPhongTroes { get; set; }
    }
}
