//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTinNguoiThue
    {
        public int TT { get; set; }
        public string HoTenNguoiThue { get; set; }
        public bool GioiTinh { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string SoDienThoai { get; set; }
        public string NgheNghiep { get; set; }
        public string NoiDKTamTru { get; set; }
        public string MaPhong { get; set; }
        public System.DateTime NgayVaoO { get; set; }
        public System.DateTime NgayHetHD { get; set; }
        public string TienDatCoc { get; set; }
        public int MaHD { get; set; }
    
        public virtual TTinPhongTro TTinPhongTro { get; set; }
    }
}
